version: "3.7"

services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 199718
      POSTGRES_USER: metatron
      POSTGRES_DB: alurareceitas
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    
volumes:
  db_data:
