# Generated by Django 4.1.2 on 2022-10-16 02:23

import django.db.models.deletion
from django.contrib.auth.models import User
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0002_classe"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="pessoa",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=User,
            ),
            preserve_default=False,
        ),
    ]
