# Generated by Django 4.1.2 on 2022-10-19 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("receitas", "0005_receita_foto_receita"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receita",
            name="pessoa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
